package seeders

var categoriesArr = []string{
	"Mathematics",
	"Physics",
	"Chemistry",
	"Biology",
	"Computer Science",
	"Economics",
	"Psychology",
	"Sociology",
	"Politics",
	"History",
	"Philosophy",
	"Linguistics",
	"Arts",
	"Literature",
	"Music",
}

var tagsArr = []string{
	"Neural Networks",
	"Deep Learning",
	"Computer Vision",
	"Natural Language Processing",
	"Reinforcement Learning",
	"Quantum Cryptography",
	"Zero-Knowledge Proofs",
	"Smart Contracts",
	"Ethical Hacking",
	"Penetration Testing",
	"Biometric Security",
	"DNA Sequencing",
	"Cloud Security",
	"Edge Computing",
	"Serverless Architecture",
	"IoT Security",
	"Big Data Analytics",
	"Data Visualization",
	"Predictive Analytics",
	"DevOps",
	"Microservices",
	"Functional Programming",
	"Distributed Systems",
	"Automated Testing",
	"Code Optimization",
	"CI/CD Pipelines",
	"Federated Learning",
	"Explainable AI",
	"Post-Quantum Cryptography",
	"Digital Twins",
	"Fourier Analysis",
	"Game Theory",
	"Mathematical Modeling",
	"Combinatorics",
	"Bayesian Inference",
	"CRISPR Technology",
	"DNA Sequencing",
	"Gene Therapy",
	"Stem Cells",
	"Synthetic Biology",
	"Radiology",
	"Bioinformatics",
	"Neuroplasticity",
	"Medical AI",
	"Quantum Biology",
	"Biostatistics",
	"Epidemiological Modeling",
	"Tissue Engineering",
	"Robotic Surgery",
	"Clinical Trials",
	"Web Development",
	"Mobile Development",
	"Cloud Computing",
	"DevOps",
	"Data Engineering",
	"Big Data",
	"Machine Learning",
	"Deep Learning",
	"Artificial Intelligence",
	"Natural Language Processing",
	"Computer Vision",
	"English Literature",
	"French Literature",
	"German Literature",
	"Spanish Literature",
	"Italian Literature",
	"Japanese Literature",
	"Chinese Literature",
	"Korean Literature",
	"Russian Literature",
	"Portuguese Literature",
	"Indonesian Literature",
	"Arabic Literature",
	"Hindi Literature",
	"Programming Languages",
	"Data Structures",
	"Chords",
	"Piano",
	"Guitar",
	"Violin",
	"Drums",
	"Bass",
	"Saxophone",
	"Violoncello",
	"Trumpet",
	"Trombone",
	"Flute",
	"Soprano",
	"Tenor",
	"Baritone",
	"Bassoon",
	"Cello",
	"Violin",
	"Piano",
	"Guitar",
	"Violin",
	"Drums",
	"Bass",
	"Saxophone",
	"Violoncello",
	"Trumpet",
	"Trombone",
	"Flute",
	"Soprano",
	"Tenor",
	"Baritone",
	"Bassoon",
	"Cello",
	"Violin",
}
